### ISSUE TITLE
模型中页码数据错误，左翻页和右翻页的页码处理也有问题。

### ISSUE THREAD

**Issue by shareGirl** [GGGHub/Reader#1]
我是在LSYReadViewController.m中打印的如下数据不准确，另外，点击某一章时，跳转没有问题，但是打印的模型数据依然不准确的。左翻页和右翻页的页码处理也有问题。
NSLog(@"readview界面  chapter= %ld  recodepage = %ld    pagecount = %ld",self.recordModel.chapter,self.recordModel.page,self.recordModel.chapterModel.pageCount);

**Comment by GGGHub** [comment]
你打印的是阅读进度，不准的原因是因为我是在翻页动画结束后保存阅读进度。而不是在显示该页时保存。至于左右翻页的问题目前还没有发现。
