### ISSUE TITLE
出现了好多错误呢~~麻烦帮我看一下 楼主~~

### ISSUE THREAD

**Issue by zhulei321470** [GGGHub/Reader#18]
Undefined symbols for architecture arm64:
  "_xmlFreeNode", referenced from:
      -[CXMLNode(CXMLNode_PrivateExtensions) invalidate] in CXMLNode_PrivateExtensions.o
  "_xmlNewPI", referenced from:
      +[CXMLNode(CXMLNode_CreationExtensions) processingInstructionWithName:stringValue:] in CXMLNode_CreationExtensions.o
  "_xmlNewNs", referenced from:
      +[CXMLNode(CXMLNode_CreationExtensions) elementWithName:URI:] in CXMLNode_CreationExtensions.o
  "_xmlNewNode", referenced from:
      +[CXMLNode(CXMLNode_CreationExtensions) elementWithName:] in CXMLNode_CreationExtensions.o
      +[CXMLNode(CXMLNode_CreationExtensions) elementWithName:URI:] in CXMLNode_CreationExtensions.o
      +[CXMLNode(CXMLNode_CreationExtensions) elementWithName:stringValue:] in CXMLNode_CreationExtensions.o
  "_xmlNewText", referenced from:
      -[CXMLElement(CXMLElement_CreationExtensions) setStringValue:] in CXMLElement_CreationExtensions.o
  "_xmlSetNs", referenced from:
      -[CXMLElement(CXMLElement_CreationExtensions) addNamespace:] in CXMLElement_CreationExtensions.o
  "_xmlNodeDumpOutput", referenced from:
      -[CXMLNode XMLStringWithOptions:] in CXMLNode.o
  "_xmlOutputBufferFlush", referenced from:
      -[CXMLNode XMLStringWithOptions:] in CXMLNode.o
  "_xmlGetCharEncodingName", referenced from:
      -[CXHTMLDocument initWithXHTMLString:options:error:] in CXHTMLDocument.o
  "_xmlDocSetRootElement", referenced from:
      -[CXHTMLDocument initWithXHTMLString:options:error:] in CXHTMLDocument.o
      +[CXMLNode(CXMLNode_CreationExtensions) documentWithRootElement:] in CXMLNode_CreationExtensions.o
  "_xmlAddChild", referenced from:
      -[CXMLDocument(CXMLDocument_CreationExtensions) addChild:] in CXMLDocument_CreationExtensions.o
      -[CXMLElement(CXMLElement_CreationExtensions) addChild:] in CXMLElement_CreationExtensions.o
      -[CXMLElement(CXMLElement_CreationExtensions) setStringValue:] in CXMLElement_CreationExtensions.o
  "_xmlAddPrevSibling", referenced from:
      -[CXMLDocument(CXMLDocument_CreationExtensions) insertChild:atIndex:] in CXMLDocument_CreationExtensions.o
  "_htmlReadMemory", referenced from:
      -[CXHTMLDocument initWithXHTMLData:encoding:options:error:] in CXHTM

**Comment by hungryAndCoder** [comment]
引入libxml2.tbd

**Comment by GGGHub** [comment]
你好请参考[README.md](https://github.com/GGGHub/Reader/blob/master/README.md)
