### ISSUE TITLE
epub 的样式用Core Text 实现

### ISSUE THREAD

**Issue by xieweizhi** [GGGHub/Reader#2]
epub 的样式用Core Text 来实现, 是不是很复杂?
现在主流的阅读器(多看, 掌阅) 应该是使用了js, html 来做的, 这样iOS, Android就可以通用一套了.

**Comment by GGGHub** [comment]
不是很复杂，实际上都是用Core Text绘制的。你可以了解一下epub文件格式，解压后都会有CSS文件。每章节会在<head>标签内引用指定的css文件。只要把css的样式解析出来用Core Text进行绘制时把这些样式加上就可以了

**Comment by xieweizhi** [comment]
那就只剩工作量咯, 感觉不是一个人能完成的工作 😂

**Comment by icloudsun** [comment]
会考虑引入第三方库DTCoreText来做吗？
