### ISSUE TITLE
解析epub文件crash

### ISSUE THREAD

**Issue by hungryAndCoder** [GGGHub/Reader#31]
LSYReadUtilites方法parseOPF加载每章的内容时，如果chapHref的值包含@号时，@"@test"，如上，原因是使用了valueForKey的KVC的方法取值，正确方法是objectForKey取值，具体原因valueForKey会去掉@符号并且sendMsg [super valueForKey]。

**Comment by GGGHub** [comment]
确实有这个问题，已经改了。谢谢了
