### ISSUE TITLE
字体修改后, 页码有问题

### ISSUE THREAD

**Issue by MrLee767201403** [GGGHub/Reader#35]
先放大字体,翻几页后, 再缩小字体,往回翻,然后数组就越界了,我暂时加了个判断,不崩了,但根本问题还是没有解决

**Comment by LambentWu** [comment]
txt文件的分页有问题，上页不接下页

**Comment by GGGHub** [comment]
fix

**Comment by tyfinal** [comment]
刚测试了下，修改字体导致闪退的问题还是存在的。

**Comment by tyfinal** [comment]
`- (nullable UIViewController *)pageViewController:(UIPageViewController *)pageViewController viewControllerBeforeViewController:(UIViewController *)viewController
{

    if (_pageIsAnimating){
        return nil;
    }
    
    _pageChange = _page;
    _chapterChange = _chapter;

    if (_chapterChange==0 &&_pageChange == 0) {
        //当前页已经是第一章第一页
        return nil;
    }
    
    if (_pageChange==0) {
        _chapterChange--;
        _pageChange = _model.chapters[_chapterChange].pageCount-1;
    }
    else{ 
        _pageChange--;
    }
    
    return [self readViewWithChapter:_chapterChange page:_pageChange];
    
}`

这里的 _pageChange = _model.chapters[_chapterChange].pageCount-1; 这样写好像有点问题。字体放大以后，所有章节的页面数都会增加。然后在当前章节下减小字体，当向前翻页到_pageChange==0 执行时，_model.chapters[_chapterChange].pageCount-1 获取的值是字体缩小前该章节的最后一页。然后执行 [self readViewWithChapter:_chapterChange page:_pageChange]，其中对章节进行了重新分页。此时的页面数目应该是小于字体减小前的页面总数的。所以导致了数组越界。不知道可看懂了，希望有时间可以看下。
