### ISSUE TITLE
书签定位问题

### ISSUE THREAD

**Issue by shmchen** [GGGHub/Reader#4]
当我保存了一个书签，改变文字大小后，书签无法准确的定位！你是根据什么机制来确定这个文字的位置的？

**Comment by GGGHub** [comment]
当前阅读的章节与页数，定位不准是由于字体改变页数也会随之改变

**Comment by shmchen** [comment]
是啊，感觉加入这个变数就复杂很多！试了下多看阅读那些，没有这个bug
