### ISSUE TITLE
iOS 11 问题

### ISSUE THREAD

**Issue by shangcezi** [GGGHub/Reader#40]
iOS 11 点击中间不显示操作栏

**Comment by ZhouguanyuIOS** [comment]
感觉是约束问题，但不知道从哪下手啊

**Comment by xuuhan** [comment]
同

**Comment by tyfinal** [comment]
我用模拟器iphonex模拟器显示能是正常的。用iphone8也不行。我跟了一下，在调用显示动画的时候，会再次调用layoutsubviews。所以没法展示出来。具体什么原因导致的我也不明白。

**Comment by risechen** [comment]
的确是操作栏没有弹出来，作者有空再更新一下，很影响使用

**Comment by GGGHub** [comment]
fix
