### ISSUE TITLE
书籍点开过一次后，在Xcode中再次运行时，书籍变为空白

### ISSUE THREAD

**Issue by hanmeng1989** [GGGHub/Reader#47]
书籍点开过一次后，在Xcode中再次运行时，已经点开过的书籍就变为空白了。这样导致我上架过的APP,如果更新版本的话，用户点开过一次的书籍就会变成空白，只能是把原来的删掉，再次重新下载才可以出现，请问这个问题怎么解决？

**Comment by Sdfeidong** [comment]
你好，请问这个问题解决了吗，有解决办法吗，谢谢！

**Comment by GGGHub** [comment]
已经修复
